//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CID { get; set; }
        public int PID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateTime { get; set; }
        public double TotalPrice { get; set; }
    }
}
